version: '3'

services:  
  ros2controller:
      build:
        context: ./
        dockerfile: ros2controller.Dockerfile
      tty: true
      network_mode: "host"
      # devices:
      #   - /dev/input/js0
      volumes:
        - ./src/rover_waypoint:/root/px4_ros_com_ros2/src/rover_waypoint